name: CI

on:
  push:
    branches:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

jobs:
  test:
    name: Unit Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: fastlane tests lane
      run: fastlane ios tests
  compatibility:
    name: DependencyManager compatibility tests
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: fastlane compatibilityTests lane
      run: fastlane ios compatibilityTests